version: '3.0'

services:
  hc_api:
    image: hc_api
    container_name: hc_api:v2.0
    restart: unless-stopped
    ports:
      - "9999:9999"
    networks:
      - hc-network

  hc_autoupdater:
    image: hc_autoupdater:v2.1
    container_name: hc_autoupdater
    restart: unless-stopped
    volumes:
      - ${HC_MAIN_DIR}:/app/src
    environment:
      - DB_HOST=${HC_DB_NAME}
      - DB_USER=${HC_DB_USER}
      - DB_PASSWORD=${HC_DB_PASSWORD}
    networks:
      - hc-network

  hc_db:
    image: hc_db:v2.3
    container_name: hc_db
    restart: unless-stopped
    volumes:
      - ${HC_DB_DIR}:/mnt
    environment:
      - SA_PASSWORD=${HC_DB_PASSWORD}
    networks:
      - hc-network
    ports:
      - "1433:1433"

networks:
  hc-network:
    driver: bridge

